Repository openwisp/ansible-openwisp2, pull requests merged in 2020-12, with the labels that each got.

#221 [feature] Added support for openwisp-firmware-upgrader #199
  README.md
  defaults/main.yml
  molecule/resources/converge.yml
  tasks/pip.yml
  templates/openwisp2/settings.py
  templates/openwisp2/urls.py
Labels: blocked

#229 [fix] Install geographic libraries separately
  tasks/apt.yml
Labels: bug

#231 [change] Pin pip to 20.2.4 to avoid new dependency resolution
  tasks/pip.yml
Labels: bug

#247 [fix] Avoid failure in load_initial_data.py if SSH vars not defined
  tasks/django.yml
  templates/load_initial_data.py
Labels: enhancement
